### ISSUE TITLE
Fix Uninitialized reads

### ISSUE THREAD

**Issue by ghost** [pinobatch/thwaite-nes#5]
It was mentioned somewhere that booting 0.03 with random memory resulted some bugs. Running a debugger that keeps track of uninitialized memory shows this is still the case. 
Things that probably need initialization:
- The practice menu selections.
- The crosshair placement and movement in practice menu.
- Missile positions when missiles first spawn

**Comment by pinobatch** [comment]
"The practice menu selections."

* The `clear_zp` loop in `main` in `main.s` implicitly initializes everything in segment `ZEROPAGE`, including `practiceDay` and `practiceHour`, to 0.
* `main` in `main.s` explicitly initializes `practiceSide` to 2 (both sides, 1 player).

"The crosshair placement and movement in practice menu."

Placement and coarse movement are initialized.

* `titleScreen` in `title.s` initializes `crosshairXHi` and `crosshairYHi`.
* `clearAllMissiles` initializes `crosshairD?[XY](Lo|Hi)` for 1 player and 2 player campaigns.
* Nothing initializes `crosshairD?[XY](Lo|Hi)` for practice.

"Missile positions when missiles first spawn"

* `clearAllMissiles` initializes `missileYHi` to 0, and the rest of the engine uses a 0 value in that variable to indicate that a missile does not exist.

You could be right that nothing initializes `crosshairD?[XY]Lo` for practice, but that has little to no visible effect. I can imagine, however, how not initializing `crosshairD[XY]Hi` could cause a minor problem with the cursor briefly sliding toward the side of the screen.

Which NES debugger supports a breakpoint on reading unwritten RAM? I know that for Game Boy, BGB has this feature.

**Comment by ghost** [comment]
Mesen supports breaking on uninitialized reads.
Sorry if I was a bit vague when I opened the issue, I didn't have debugging symbols from ca65 setup to see clearly.
Aside: in the make file add `-g` to `CFLAGS65`and `--dbgfile $(title).dbg` to the LD65 commands

`titleScreen` does initialize but not before `title_detect_mice` in `display_todo`

what's tripping up the debugger for Missiles is actually because `missileXLo,X` isn't initialized by the time the missile vectors are applied in `moveMissileNumberX`

~~Crosshair location is definitely not initialized in the practice menu, I noticed this visually first before I started using breakpoints. (also caused my recorded button presses, that I was going to use for another issue, to desync)~~ (fixed in commit)

Uninitialized `levelSalvoSizes,Y` in `drawPracticeMenuSprites` can also cause some jumbled graphics.

**Comment by pinobatch** [comment]
Two of the uninitialized RAM reads that Mesen detects have no visible effect: uninitialized `OAM[x]` where `x % 4 != 0 && OAM[x & 0xFC] >= 0xF0`, and uninitialized cursor position during `display_todo` (the copyright screen). I've put these two behind a "pedantic RAM clearing" switch in `global.inc` in case we need to save a few bytes later.

Any left?

**Comment by ghost** [comment]
Only things left I see are the X subpixel positions for split missile spawning and player shots.

(and a few unnecessary pedantic considerations for variables in zero page)

**Comment by pinobatch** [comment]
Anything to fix after eb0533cf889f5b52596b744deacdf422d28731f1?

**Comment by ghost** [comment]
Not that I see.

Closing Issue.
